version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mongo:
    image: mongo
    networks:
      - app
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: db
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017'

  phpfpm:
    image: itkdev/php7.3-fpm
    networks:
      - app
    environment:
      - PHP_XDEBUG=${PHP_XDEBUG:-0}
      - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
      - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - PHP_IDE_CONFIG=serverName=localhost
    depends_on:
      - mongo
    volumes:
      - .:/app:delegated
    tmpfs:
      - /app/var/cache:size=1G
      - /tmp:size=1G

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  redis:
    image: 'redis:4'
    networks:
      - app
    ports:
      - '6379'

  elasticsearch:
    image: 'elasticsearch:6.8.4'
    networks:
      - app
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD="password"
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - ${PWD}/.docker/es:/usr/share/elasticsearch/data:rw
    ports:
      - '9200'
      - '9300'

  rabbit:
    image: rabbitmq:3-management
    networks:
      - app
      - frontend
    ports:
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE='d53f319cd7376f8f840aaf9889f315ab'